/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Sat Aug 17 23:26:03 2019. */

#include "FileListResult.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t FileInfo_fields[4] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, FileInfo, name, name, 0),
    PB_FIELD(  2, BOOL    , REQUIRED, STATIC  , OTHER, FileInfo, isFolder, name, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, FileInfo, size, isFolder, 0),
    PB_LAST_FIELD
};

const pb_field_t FileListResult_fields[4] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, FileListResult, folder, folder, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, FileListResult, total, folder, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, STATIC  , OTHER, FileListResult, files, total, &FileInfo_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(FileListResult, files[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_FileInfo_FileListResult)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(FileListResult, files[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_FileInfo_FileListResult)
#endif


/* @@protoc_insertion_point(eof) */
