/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Mon Aug 12 15:03:04 2019. */

#include "FlasherParams.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t FlasherParams_fields[3] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, FlasherParams, ir, ir, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, FlasherParams, white, ir, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
