/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Sat Aug 17 23:26:03 2019. */

#include "RegisterFaceIdWithPicParams.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t RegisterFaceIdWithPicParams_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, RegisterFaceIdWithPicParams, faceName, faceName, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, RegisterFaceIdWithPicParams, filePath, faceName, 0),
    PB_LAST_FIELD
};

const pb_field_t RegisterFaceIdFromCameraParams_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, RegisterFaceIdFromCameraParams, faceName, faceName, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, RegisterFaceIdFromCameraParams, timeoutMs, faceName, 0),
    PB_LAST_FIELD
};

const pb_field_t SetFaceIdParams_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SetFaceIdParams, faceId, faceId, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, SetFaceIdParams, faceName, faceId, 0),
    PB_LAST_FIELD
};

const pb_field_t ListFaceIdParams_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, ListFaceIdParams, start, start, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, ListFaceIdParams, length, start, 0),
    PB_LAST_FIELD
};

const pb_field_t FaceIdInfo_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, FaceIdInfo, faceId, faceId, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, FaceIdInfo, faceName, faceId, 0),
    PB_LAST_FIELD
};

const pb_field_t FaceIdListData_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, FaceIdListData, start, start, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, STATIC  , OTHER, FaceIdListData, faces, start, &FaceIdInfo_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(FaceIdListData, faces[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_RegisterFaceIdWithPicParams_RegisterFaceIdFromCameraParams_SetFaceIdParams_ListFaceIdParams_FaceIdInfo_FaceIdListData)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(FaceIdListData, faces[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_RegisterFaceIdWithPicParams_RegisterFaceIdFromCameraParams_SetFaceIdParams_ListFaceIdParams_FaceIdInfo_FaceIdListData)
#endif


/* @@protoc_insertion_point(eof) */
