/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Thu Jun 27 18:53:26 2019. */

#include "RegisterFaceIdWithPicParams.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t RegisterFaceIdWithPicParams_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, RegisterFaceIdWithPicParams, faceId, faceId, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, RegisterFaceIdWithPicParams, filePath, faceId, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
