/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.2 at Sat Aug 17 23:26:03 2019. */

#ifndef PB_FLASHERPARAMS_PB_H_INCLUDED
#define PB_FLASHERPARAMS_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _FlasherParams {
    bool has_ir;
    int32_t ir;
    bool has_white;
    int32_t white;
/* @@protoc_insertion_point(struct:FlasherParams) */
} FlasherParams;

/* Default values for struct fields */

/* Initializer values for message structs */
#define FlasherParams_init_default               {false, 0, false, 0}
#define FlasherParams_init_zero                  {false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define FlasherParams_ir_tag                     1
#define FlasherParams_white_tag                  2

/* Struct field encoding specification for nanopb */
extern const pb_field_t FlasherParams_fields[3];

/* Maximum encoded size of messages (where known) */
#define FlasherParams_size                       22

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define FLASHERPARAMS_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
